//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cbt_diary_bot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Emotions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Emotions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cbt_diary_bot.Emotions", typeof(Emotions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гнев.
        /// </summary>
        public static string Anger {
            get {
                return ResourceManager.GetString("Anger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тоска.
        /// </summary>
        public static string Anguish {
            get {
                return ResourceManager.GetString("Anguish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тревога.
        /// </summary>
        public static string Anxiety {
            get {
                return ResourceManager.GetString("Anxiety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Апатия.
        /// </summary>
        public static string Apathy {
            get {
                return ResourceManager.GetString("Apathy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Презрение.
        /// </summary>
        public static string Contempt {
            get {
                return ResourceManager.GetString("Contempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недовольство.
        /// </summary>
        public static string Discontent {
            get {
                return ResourceManager.GetString("Discontent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отвращение.
        /// </summary>
        public static string Disgust {
            get {
                return ResourceManager.GetString("Disgust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страх.
        /// </summary>
        public static string Fear {
            get {
                return ResourceManager.GetString("Fear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уныние.
        /// </summary>
        public static string Gloom {
            get {
                return ResourceManager.GetString("Gloom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вина.
        /// </summary>
        public static string Guilt {
            get {
                return ResourceManager.GetString("Guilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возмущение.
        /// </summary>
        public static string Indignation {
            get {
                return ResourceManager.GetString("Indignation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Раздражение.
        /// </summary>
        public static string Irritation {
            get {
                return ResourceManager.GetString("Irritation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паника.
        /// </summary>
        public static string Panic {
            get {
                return ResourceManager.GetString("Panic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ярость.
        /// </summary>
        public static string Rage {
            get {
                return ResourceManager.GetString("Rage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обида.
        /// </summary>
        public static string Resentment {
            get {
                return ResourceManager.GetString("Resentment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грусть.
        /// </summary>
        public static string Sadness {
            get {
                return ResourceManager.GetString("Sadness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стыд.
        /// </summary>
        public static string Shame {
            get {
                return ResourceManager.GetString("Shame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страдание.
        /// </summary>
        public static string Suffering {
            get {
                return ResourceManager.GetString("Suffering", resourceCulture);
            }
        }
    }
}
